### ISSUE TITLE
Helm Hydra secrets failing

### ISSUE THREAD

**Issue by saul-gush** [ory/k8s#155]
Followed the instructions to create a secret, secret created OK but helm chart fails with. I can install other helm charts OK.

Error: create: failed to create: Secret "sh.helm.release.v1.hydra.existingSecret=my-secret.v1" is invalid: [metadata.name: Invalid value: "sh.helm.release.v1.hydra.existingSecret=my-secret.v1": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.labels: Invalid value: "hydra.existingSecret=my-secret": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]

helm install -f ./hydraconfig.yaml  \
    --set 'ingress.public.enabled=true' \
    --set 'ingress.admin.enabled=true' \
    --set 'hydra.dangerousForceHttp=true' \
    --set 'hydra.autoMigrate=true' \
    'hydra.existingSecret=my-secret' \
    ory/hydra

**Comment by saul-gush** [comment]
OK I managed to figure this out but init containers on auto migrate are still failing for secrets. I really think the Hydra documentation in general needs to be more user friendly and cleaned up. It is taking ages to work out simple things. 

Fixed helm install:
```shell script
helm install -f ./hydraconfig.yaml --kube-context=$(kubectl config current-context) \
    --set 'ingress.public.enabled=true' \
    --set 'ingress.admin.enabled=true' \
    --set 'hydra.dangerousForceHttp=true' \
    --set 'hydra.autoMigrate=true' \
    --set 'hydra.existingSecret=gush-secret' \
    --generate-name \
    ory/hydra
```

```
Init Containers:
  hydra-automigrate:
    Container ID:
    Image:         oryd/hydra:v1.4.6
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      hydra
    Args:
      migrate
      sql
      -e
      --yes
      --config
      /etc/config/config.yaml
    State:          Waiting
      Reason:       CreateContainerConfigError
    Ready:          False
    Restart Count:  0
    Environment:
      DSN:  <set to the key 'dsn' in secret 'hydra-1593876668'>  Optional: false
    Mounts:
      /etc/config from hydra-config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-2bdhv (ro)
```

**Comment by aeneasr** [comment]
Where did you get `existingSecret` from? I don't think we have documented that anywhere. If you check out the Kubernetes Helm Charts, it has an [example with all the required config](https://k8s.ory.sh/helm/hydra.html):

```
$ helm install \
    --set 'hydra.config.secrets.system=$(LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | base64 | head -c 32)' \
    --set 'hydra.config.dsn=memory' \
    --set 'hydra.config.urls.self.issuer=https://my-hydra/' \
    --set 'hydra.config.urls.login=https://my-idp/login' \
    --set 'hydra.config.urls.consent=https://my-idp/consent' \
    ory/hydra
```

Critique is always welcomed, and we encourage contributions to the documentation even more!

**Comment by aeneasr** [comment]
`existingSecret` can be used to point to an existing kubernetes secret, it's not the actual secret. Your first command failed because you forgot a `--set`:

```
 helm install -f ./hydraconfig.yaml 
 --set 'ingress.public.enabled=true' 
 --set 'ingress.admin.enabled=true' 
 --set 'hydra.dangerousForceHttp=true' 
 --set 'hydra.autoMigrate=true' 
-'hydra.existingSecret=my-secret' 
+--set 'hydra.existingSecret=my-secret' 
 ory/hydra
```

**Comment by saul-gush** [comment]
If I find some time I will try improve the documents. The document describing existing secrets is here: https://k8s.ory.sh/helm/hydra.html

I think what is better is to not use helm charts. Much simpler to use K8s yaml files. If I get a chance, I will send some examples.

I spent about 2 weeks trying to integrate Krato and Hydra - its not that simple! I'd like to think that Im pretty good with these things. Says its only a few lines of code in the landing pages but I beg to differ. I think your team are very close to the detaols and how this works, for someone new, its very very hard to get going. This will hurt your adoption rates for sure. I love the concept behind Krato/Hydra but it is making me nervous because if I mess up one of the configurations because of its complexity, I mess up my user experience and security in the platform. I am also spending waaay too much time trying to get it to work.

**Comment by aeneasr** [comment]
But it clearly states in that document that this is how to set up Hydra:

```
$ helm install \
    --set 'hydra.config.secrets.system=$(LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | base64 | head -c 32)' \
    --set 'hydra.config.dsn=memory' \
    --set 'hydra.config.urls.self.issuer=https://my-hydra/' \
    --set 'hydra.config.urls.login=https://my-idp/login' \
    --set 'hydra.config.urls.consent=https://my-idp/consent' \
    ory/hydra
```

Is that not working for you? If not, then there's a bug and we should resolve it. The `existingSecret` section says:

> Alternatively, you can use an existing kubernetes secret:

Implying a https://kubernetes.io/docs/concepts/configuration/secret/

If something there is broken we should address and fix it, it is totally possible that e.g. `existingSecret` does not work for automigration because of a bug.

Kuberentes Helm Charts are good for open source projects while regular Kubernetes configs are good for open source projects with many config options.

> I spent about 2 weeks trying to integrate Krato and Hydra - its not that simple! 

Kratos is a very early project (0.3.0 alpha), many use cases are not yet implemented - direct integration with ORY Hydra is on the roadmap (https://github.com/ory/kratos/issues/273). It is possible to implement an integration but if you've never worked with either one before it's obviously going to be hard :)

So there's tons of work ahead and we want to encourage everyone to participate in improving the developer experience!

**Comment by saul-gush** [comment]
Sorry I should have mentioned that I did get the existingsecret to work and that works fine. You do need to update your documentation at https://k8s.ory.sh/helm/hydra.html to include --set

On developer friendliness point, Hydra isn't simple either... :) Have a look at Stripe, they are excellent at taking something really complex and making it simple for everyone. This should be the same IMO.

**Comment by aeneasr** [comment]
The problem is that a payment SaaS with proprietary APIs is not an open standard defined by various entities (IETF, OpenID Foundation) and that OAuth2 and OpenID Connect in general are fucking hard - no matter what product you use. 99% of use cases don't need OAuth2 or OpenID Connect but think they do because they saw an advert from Auth0 or Okta. What almost every developer is looking for is Single Sign On, and that's what we're solving with ORY Kratos.

If you need OAuth2 and you want to become an OpenID Connect Provider like Google or Facebook do, there is simply no quick out for you!

**Comment by aeneasr** [comment]
Given that this is working now as you expected, and that I've updated the docs, this is considered resolved.
