### ISSUE TITLE
Readiness check returns 503

### ISSUE THREAD

**Issue by bzlom** [ory/k8s#269]
When deploying Kratos Helm Chart the pod doesn't start due to readiness check returning 503 errors (the health check completes successfully):
time=2021-05-24T10:06:21Z level=info msg=completed handling request http_request=map[headers:map[accept-encoding:gzip user-agent:kube-probe/1.18+] host:10.5.91.184:4434 method:GET path:/health/ready query:<nil> remote:10.5.94.194:56050 scheme:http] http_response=map[status:503 text_status:Service Unavailable took:375.510136ms]

Default deployment through Helm, no special attributes were added

Expected behavior:
The readiness check to pass and the pod to start. 

Environment:
Environment: Amazon EKS 1.18

**Comment by aeneasr** [comment]
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Please also ensure that your issue is appropriately formatted. If you do not know how to write markdown, you can find help [here](https://guides.github.com/features/mastering-markdown/).

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment. 

> Do not edit the original post as we will not be notified when you do so.

If you do not provide the requested information, this issue will be closed.

**Comment by JeffreyThijs** [comment]
This is probably due to the too short `timeoutSeconds` of the readiness probe (had the same issue), although i could be wrong. PR #268 should help to resolve this.

**Comment by aeneasr** [comment]
#268 was merged!
